name: phpstan
on:
  - push
  - pull_request

jobs:
  analyze:
    runs-on: ubuntu-20.04
    name: analyze
    steps:
      - uses: actions/checkout@v2
      - run: mkdir ../php
      - run: curl -L https://get.pmmp.io | bash
        working-directory: ../php
        name: Install PHP
      - run: ln -s ../php/bin/php7/bin/php php
      - run: curl https://getcomposer.org/installer | ./php
        name: Install Composer
      - run: ./php composer.phar install
        name: Install dependencies
      - run: ./php vendor/bin/phpstan analyze
        name: Perform analysis
